plugins:
  app_petition_category_id:
    type: category_list
    default: 1
    client: true
  app_category_id:
    type: category_list
    default: 1
    client: true
  app_default:
    default: 'civically-navigation|civically-place|civically-user|civically-site'
  app_default_image_url:
    default: '/plugins/civically-app/images/default-app-image.png'
